FROM node:20-alpine AS build
WORKDIR /app
COPY grimorio-front/package*.json ./
RUN npm install
COPY grimorio-front/ ./
RUN npm run build

FROM nginx:alpine AS final
COPY --from=build /app/dist /usr/share/nginx/html
RUN echo 'server { \
  listen 80; \
  location /api { \
    proxy_pass http://back:5000; \
    proxy_set_header Host $host; \
    proxy_set_header X-Real-IP $remote_addr; \
  } \
  location / { \
    root /usr/share/nginx/html; \
    index index.html; \
    try_files $uri $uri/ /index.html; \
  } \
}' > /etc/nginx/conf.d/default.conf
EXPOSE 80
